name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build the site using jekyll/builder Docker container
      - name: Build Site with Jekyll in Docker
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      # Optional: Upload _site output as an artifact (for Netlify or manual deploy)
      - name: Upload Site Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site
